local myVar = std.extVar("input.myVar");
{
  "kind": "pipeline",
  "type": "exec",
  "name": "default",
  "clone": { "disable": true },
  "steps": [
    {
      "name": "step1",
      "commands": [
        myVar
      ]
    }
  ]
}
